/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\01-CURIOSITY.glb --transfrom --keepnames 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/01-CURIOSITY.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.PC} position={[-0.201, 0, 0.713]} rotation={[0, 0.772, 0]} scale={0.232} />
      <mesh name="Book" geometry={nodes.Book.geometry} material={materials.BookStack} position={[0.248, 0, 1.098]} rotation={[0, 0.972, 0]} scale={[0.193, 0.031, 0.222]} />
      <mesh name="Calculator" geometry={nodes.Calculator.geometry} material={materials.Calcilator} position={[0.512, 0, 0.761]} rotation={[0, 0.262, 0]} scale={[0.152, 0.005, 0.079]} />
      <mesh name="Rings" geometry={nodes.Rings.geometry} material={nodes.Rings.material} position={[0.651, 0.015, 0.334]} rotation={[Math.PI / 2, 0, -2.145]} scale={0.013} />
      <mesh name="Paper" geometry={nodes.Paper.geometry} material={nodes.Paper.material} position={[0.495, 0.007, 0.435]} rotation={[-0.03, 0.577, 0.017]} scale={[0.194, 0.118, 0.138]} />
      <mesh name="Pen" geometry={nodes.Pen.geometry} material={materials.pencil} position={[0.467, 0.025, 0.179]} rotation={[1.56, 0, 0.565]} scale={[0.003, 0.067, 0.003]} />
      <mesh name="Cup" geometry={nodes.Cup.geometry} material={materials.Cup} position={[0.303, 0, 0.077]} rotation={[0, 0.437, 0]} scale={0.062} />
      <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.Wood} position={[1.457, 0, 0]} scale={[2.024, 2.024, 1.777]} />
      <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.Bookslogos} position={[0.063, 0, -0.232]} rotation={[-Math.PI, 0.822, -Math.PI]} scale={[0.248, 0.028, 0.293]} />
      <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[0.144, 0.112, -0.417]} scale={-0.007} />
      <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[0.403, 0.029, -0.287]} rotation={[0, 0.695, 0]} scale={[-0.016, -0.031, -0.012]} />
      <mesh name="Sticker2" geometry={nodes.Sticker2.geometry} material={nodes.Sticker2.material} position={[-0.133, 0.112, -0.189]} scale={[0.055, 0.056, 0.055]} />
      <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={nodes.Plane005.material} position={[0.144, 0.112, -0.417]} rotation={[0.137, 0.518, -0.075]} scale={[0.083, 0.054, 0.064]} />
      <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[0.144, 0.112, -0.417]} rotation={[0.05, 0.524, -0.026]} scale={[0.083, 0.054, 0.064]} />
      <mesh name="Sticker1" geometry={nodes.Sticker1.geometry} material={nodes.Sticker1.material} position={[0.015, 0.112, -0.064]} scale={[0.055, 0.056, 0.055]} />
      <mesh name="Sticker3" geometry={nodes.Sticker3.geometry} material={nodes.Sticker3.material} position={[0.155, 0.112, -0.19]} scale={[0.055, 0.056, 0.055]} />
      <mesh name="Sticker4" geometry={nodes.Sticker4.geometry} material={nodes.Sticker4.material} position={[0, 0.112, -0.323]} scale={[0.055, 0.056, 0.055]} />
      <mesh name="Sticker5" geometry={nodes.Sticker5.geometry} material={nodes.Sticker5.material} position={[0.255, 0.112, -0.313]} scale={[0.055, 0.056, 0.055]} />
      <mesh name="Frame" geometry={nodes.Frame.geometry} material={nodes.Frame.material} scale={0.707} />
    </group>
  )
}

useGLTF.preload('/01-CURIOSITY.glb')
