/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\Coffin.glb --transform --keepmeshes 
Files: .\public\Coffin.glb [39.53MB] > C:\Users\TresSillings\Projects\The Lab\the-lab-alpha\Coffin-transformed.glb [2.72MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Coffin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Coffin.geometry} material={materials.White_Marble} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Black_Marble} position={[0, 0, -0.077]} scale={0.009} />
      <mesh geometry={nodes.Metal.geometry} material={materials['Brushed used metal silver']} position={[0.002, 0.113, 0.582]} rotation={[0.602, 0, 0]} scale={[0.807, 0.009, 0.194]} />
      <mesh geometry={nodes.Metal_Inside.geometry} material={materials['Brushed used metal silver']} position={[0, 0.024, -0.423]} scale={[0.914, 0.173, 0.325]} />
    </group>
  )
}

useGLTF.preload('/Coffin-transformed.glb')
