/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\Coffin.glb --transform --keepmeshes 
Files: .\public\Coffin.glb [38.84MB] > C:\Users\TresSillings\Projects\The Lab\the-lab-alpha\Coffin-transformed.glb [6.06MB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Coffin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Coffin.geometry} material={materials.White_Marble} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Black_Marble} position={[0, 0, -0.077]} scale={0.009} />
      <mesh geometry={nodes.Metal.geometry} material={materials['Brushed used metal silver']} position={[0.002, 0.113, 0.582]} rotation={[0.602, 0, 0]} scale={[0.807, 0.009, 0.194]} />
      <mesh geometry={nodes.Metal_Inside.geometry} material={materials['Brushed used metal silver']} position={[0, 0.024, -0.423]} scale={[0.914, 0.173, 0.325]} />
      <mesh geometry={nodes.OrnateHandle1.geometry} material={nodes.OrnateHandle1.material} position={[0.495, 0.241, 0.326]} rotation={[-1.579, 0, 0]} scale={0.165} />
      <mesh geometry={nodes.OrnateHandle3.geometry} material={nodes.OrnateHandle3.material} position={[-0.497, 0.241, 0.326]} rotation={[-1.579, 0, 0]} scale={0.165} />
      <mesh geometry={nodes.OrnateHandle4.geometry} material={nodes.OrnateHandle4.material} position={[0.495, -0.084, 0.791]} rotation={[-0.571, 0, 0]} scale={0.165} />
      <mesh geometry={nodes.OrnateHandle6.geometry} material={nodes.OrnateHandle6.material} position={[-0.494, -0.084, 0.791]} rotation={[-0.571, 0, 0]} scale={0.165} />
      <mesh geometry={nodes.OrnateHandle2.geometry} material={nodes.OrnateHandle2.material} position={[-0.005, 0.241, 0.326]} rotation={[-1.579, 0, 0]} scale={0.165} />
      <mesh geometry={nodes.OrnateHandle5.geometry} material={nodes.OrnateHandle5.material} position={[0, -0.084, 0.791]} rotation={[-0.571, 0, 0]} scale={0.165} />
      <mesh geometry={nodes.StandardHandle1.geometry} material={nodes.StandardHandle1.material} position={[0.495, 0.241, 0.326]} rotation={[1.452, 0.004, 0]} scale={0.164} />
      <mesh geometry={nodes.StandardHandle3.geometry} material={nodes.StandardHandle3.material} position={[-0.497, 0.241, 0.326]} rotation={[1.452, 0.004, 0]} scale={0.164} />
      <mesh geometry={nodes.StandardHandle2.geometry} material={nodes.StandardHandle2.material} position={[-0.005, 0.241, 0.326]} rotation={[1.452, 0.004, 0]} scale={0.164} />
      <mesh geometry={nodes.StandardHandle1001.geometry} material={nodes.StandardHandle1001.material} position={[0.495, -0.087, 0.789]} rotation={[3.08, 0.004, 0]} scale={0.164} />
      <mesh geometry={nodes.StandardHandle3001.geometry} material={nodes.StandardHandle3001.material} position={[-0.497, -0.087, 0.789]} rotation={[3.08, 0.004, 0]} scale={0.164} />
      <mesh geometry={nodes.StandardHandle2001.geometry} material={nodes.StandardHandle2001.material} position={[-0.005, -0.087, 0.789]} rotation={[3.08, 0.004, 0]} scale={0.164} />
      <mesh geometry={nodes.NamePlate.geometry} material={nodes.NamePlate.material} position={[-0.63, 0.119, 0.586]} rotation={[-0.96, 0, Math.PI / 2]} scale={0.164} />
      <mesh geometry={nodes.OrnateNameplate.geometry} material={nodes.OrnateNameplate.material} position={[-0.63, 0.119, 0.586]} rotation={[-0.96, 0, Math.PI / 2]} scale={0.164} />
      <mesh geometry={nodes.PlasticHandle.geometry} material={nodes.PlasticHandle.material} position={[0.495, 0.241, 0.326]} rotation={[Math.PI / 2, 0, 0]} scale={0.164} />
      <mesh geometry={nodes.PlasticHandle001.geometry} material={nodes.PlasticHandle001.material} position={[-0.497, 0.241, 0.326]} rotation={[Math.PI / 2, 0, 0]} scale={0.164} />
      <mesh geometry={nodes.PlasticHandle002.geometry} material={nodes.PlasticHandle002.material} position={[-0.005, 0.241, 0.326]} rotation={[Math.PI / 2, 0, 0]} scale={0.164} />
      <mesh geometry={nodes.PlasticHandle003.geometry} material={nodes.PlasticHandle003.material} position={[0.495, -0.084, 0.791]} rotation={[2.656, 0, 0]} scale={0.164} />
      <mesh geometry={nodes.PlasticHandle004.geometry} material={nodes.PlasticHandle004.material} position={[0, -0.084, 0.791]} rotation={[2.656, 0, 0]} scale={0.164} />
      <mesh geometry={nodes.PlasticHandle005.geometry} material={nodes.PlasticHandle005.material} position={[-0.494, -0.084, 0.791]} rotation={[2.656, 0, 0]} scale={0.164} />
    </group>
  )
}

useGLTF.preload('/Coffin-transformed.glb')
