/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\Floor.glb --transform 
Files: .\public\Floor.glb [15.57MB] > C:\Users\TresSillings\Projects\The Lab\the-lab-alpha\Floor-transformed.glb [631.99KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Floor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.TechFloor} rotation={[0, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/Floor-transformed.glb')
