/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\TresSillings\Projects\The Lab\SwordTheLab.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SwordTheLab.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.039, 0]} scale={0.01}>
        <mesh geometry={nodes.Blade_1.geometry} material={materials.weaponMap_MAT} />
        <mesh geometry={nodes.Handle_1.geometry} material={materials.weaponMap_MAT} />
        <mesh geometry={nodes.Hilt_1.geometry} material={materials.weaponMap_MAT} />
      </group>
      <group position={[0, 0.04, 0]} scale={0.01}>
        <mesh geometry={nodes.Blade_2.geometry} material={materials.weaponMap_MAT} />
        <mesh geometry={nodes.Handle_2.geometry} material={materials.weaponMap_MAT} />
        <mesh geometry={nodes.Hilt_2.geometry} material={materials.weaponMap_MAT} />
      </group>
      <group position={[0, 0.04, 0]} scale={0.01}>
        <mesh geometry={nodes.Blade_3.geometry} material={materials.weaponMap_MAT} />
        <mesh geometry={nodes.Handle_3.geometry} material={materials.weaponMap_MAT} />
        <mesh geometry={nodes.Hilt_3.geometry} material={materials.weaponMap_MAT} />
      </group>
      <group position={[0, 0.04, 0]} scale={0.01}>
        <mesh geometry={nodes.Blade_4.geometry} material={materials.weaponMap_MAT} />
        <mesh geometry={nodes.Handle_4.geometry} material={materials.weaponMap_MAT} />
        <mesh geometry={nodes.Hilt_4.geometry} material={materials.weaponMap_MAT} />
      </group>
    </group>
  )
}

useGLTF.preload('/SwordTheLab.glb')
