/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\Mannequin.glb --transform 
Files: .\public\Mannequin.glb [1.81MB] > C:\Users\TresSillings\Projects\The Lab\the-lab-alpha\Mannequin-transformed.glb [1.31MB] (28%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mannequin(props) {
  // Use a global path starting from / for files in the public folder
  const { nodes, materials } = useGLTF('/Mannequin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.clavicle_right_.geometry} material={materials['bone multi material ']} position={[-0.043, 1.487, -0.034]} rotation={[0, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/Mannequin-transformed.glb')
