/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\TShirt_01.glb --transform 
Files: .\public\TShirt_01.glb [3.64MB] > C:\Users\TresSillings\Projects\The Lab\the-lab-alpha\TShirt_01-transformed.glb [857.35KB] (76%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TShirt_01-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Comfortable_T-Shirt'].geometry} material={materials.K_Jersey_100Ctn_110GSM_S_DF22016_FRONT_2869} position={[-0.043, 1.164, -0.037]} rotation={[Math.PI, 0, Math.PI]} scale={1.534} />
    </group>
  )
}

useGLTF.preload('/TShirt_01-transformed.glb')
