/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\rooomtestthing.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rooomtestthing.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.915, 0.76, 0.915]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Foot.geometry} material={materials.BlackPlastic} position={[0, 0.251, 0.024]} />
        <mesh geometry={nodes.Handles.geometry} material={materials.BlackPlastic} position={[0.145, 0.2, 0.018]} rotation={[-0.217, 0, 0]} />
        <mesh geometry={nodes.Screen.geometry} material={materials.Screen} position={[0, 0.244, 0.013]} rotation={[1.353, 0, 0]} />
        <mesh geometry={nodes.Screen2.geometry} material={materials.BlackPlastic} position={[0, 0.244, 0.013]} rotation={[1.353, 0, 0]}>
          <mesh geometry={nodes.Cutter.geometry} material={nodes.Cutter.material} position={[0.145, -0.012, 0]} rotation={[0, 0, Math.PI]} scale={[1, 1, 0.872]} />
        </mesh>
      </group>
      <group position={[0.89, 0.762, 0.683]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['keyboard key.001']} position={[-0.015, 0.023, 0.171]} />
        <mesh geometry={nodes.Cube006.geometry} material={materials['keyboard key.001']} position={[0.007, 0.023, 0.165]} />
        <mesh geometry={nodes.Cube007.geometry} material={materials['keyboard key.001']} position={[0.029, 0.023, 0.176]} />
        <mesh geometry={nodes.Cube008.geometry} material={materials['keyboard key.001']} position={[-0.035, 0.023, 0.2]} />
        <mesh geometry={nodes.Cube009.geometry} material={materials['keyboard key.001']} position={[-0.058, 0.023, 0.164]} />
        <mesh geometry={nodes.Cube010.geometry} material={materials['keyboard key.001']} position={[-0.058, 0.023, 0.067]} />
        <mesh geometry={nodes.Cube011.geometry} material={materials['keyboard key.001']} position={[-0.058, 0.023, -0.032]} />
        <mesh geometry={nodes.Cube012.geometry} material={materials['keyboard key.001']} position={[-0.056, 0.023, 0.232]} />
        <mesh geometry={nodes.Cube013.geometry} material={materials['keyboard key.001']} position={[-0.058, 0.023, 0.199]} />
        <mesh geometry={nodes.Cube014.geometry} material={materials['keyboard key.001']} position={[-0.014, 0.023, 0.201]} />
        <mesh geometry={nodes.Cube015.geometry} material={materials['keyboard key.001']} position={[0.007, 0.023, 0.201]} />
        <mesh geometry={nodes.Cube016.geometry} material={materials['keyboard key.001']} position={[0.029, 0.023, 0.199]} />
        <mesh geometry={nodes.Cube017.geometry} material={materials['keyboard key.001']} position={[0.05, 0.023, 0.201]} />
        <mesh geometry={nodes.Cube018.geometry} material={materials['keyboard key.001']} position={[0.05, 0.023, 0.173]} />
        <mesh geometry={nodes.Cube019.geometry} material={materials['keyboard key.001']} position={[0.05, 0.023, 0.145]} />
        <mesh geometry={nodes.Cube020.geometry} material={materials['keyboard key.001']} position={[0.05, 0.023, -0.005]} />
        <mesh geometry={nodes.Cube021.geometry} material={materials['keyboard key.001']} position={[0.05, 0.023, -0.033]} />
        <mesh geometry={nodes.Cube022.geometry} material={materials['keyboard key.001']} position={[0.05, 0.023, -0.061]} />
        <mesh geometry={nodes.Cube023.geometry} material={materials['keyboard key.001']} position={[0.05, 0.023, -0.088]} />
        <mesh geometry={nodes.Cube024.geometry} material={materials['keyboard key.001']} position={[0.028, 0.023, -0.088]} />
        <mesh geometry={nodes.Cube025.geometry} material={materials['keyboard key.001']} position={[-0.035, 0.023, -0.077]} />
        <mesh geometry={nodes.Cube026.geometry} material={materials['keyboard key.001']} position={[-0.058, 0.023, -0.124]} />
        <mesh geometry={nodes.Cube027.geometry} material={materials['keyboard key.001']} position={[-0.036, 0.023, -0.124]} />
        <mesh geometry={nodes.Cube028.geometry} material={materials['keyboard key.001']} position={[-0.016, 0.023, -0.124]} />
        <mesh geometry={nodes.Cube029.geometry} material={materials['keyboard key.001']} position={[0.05, 0.023, -0.126]} />
        <mesh geometry={nodes.Cube030.geometry} material={materials['keyboard key.001']} position={[0.029, 0.023, -0.146]} />
        <mesh geometry={nodes.Cube031.geometry} material={materials['keyboard key.001']} position={[-0.036, 0.023, -0.197]} />
        <mesh geometry={nodes.Cube032.geometry} material={materials['keyboard key.001']} position={[0.05, 0.023, 0.088]} />
        <mesh geometry={nodes.Cube033.geometry} material={materials['keyboard key.001']} position={[-0.015, 0.023, -0.087]} />
        <mesh geometry={nodes.Cube034.geometry} material={materials['keyboard key.001']} position={[0.048, 0.023, -0.197]} />
        <mesh geometry={nodes.Cube035.geometry} material={materials['keyboard key.001']} position={[0.048, 0.023, -0.238]} />
        <mesh geometry={nodes.Cube036.geometry} material={materials['keyboard key.001']} position={[0.03, 0.023, -0.259]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube037.geometry} material={materials['keyboard key.001']} position={[-0.012, 0.023, -0.259]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Cube038.geometry} material={materials['keyboard key.001']} position={[-0.036, 0.023, -0.259]} />
        <mesh geometry={nodes.Cube039.geometry} material={materials['keyboard key.001']} position={[-0.061, 0.014, -0.197]} />
        <mesh geometry={nodes.Cube040.geometry} material={materials['keyboard key.001']} position={[-0.093, 0.014, -0.214]} />
        <group position={[-0.092, -0.002, -0.149]}>
          <mesh geometry={nodes.Cube135.geometry} material={materials['keyboard key.001']} />
          <mesh geometry={nodes.Cube135_1.geometry} material={materials['keyboard.001']} />
          <mesh geometry={nodes.Cube135_2.geometry} material={materials['rubber.002']} />
        </group>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['keyboard key.001']} position={[-0.092, 0.015, -0.103]} />
        <group position={[-0.092, 0.016, -0.159]}>
          <mesh geometry={nodes.Cylinder007.geometry} material={materials['LIGHT on.001']} />
          <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['LIGHT off.001']} />
        </group>
      </group>
      <mesh geometry={nodes.Floor.geometry} material={materials['Wood Floor.001']} />
      <mesh geometry={nodes.Walls.geometry} material={materials['Painted Wall Procedural']} />
      <mesh geometry={nodes.Desk_Trigger.geometry} material={materials['Material.103']} position={[0.856, 0.828, 0.536]} scale={[1, 1, 0.526]} />
      <group position={[0.876, 0, 0.736]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Desk.geometry} material={materials.DeskBody} />
        <mesh geometry={nodes.Desk_1.geometry} material={materials.TableTop} />
        <mesh geometry={nodes.Desk_2.geometry} material={materials.Handle} />
      </group>
    </group>
  )
}

useGLTF.preload('/rooomtestthing.glb')
