/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\Shoethelab.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Shoethelab.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Laces_R.geometry} material={materials.MAT_Laces_R} />
      <mesh geometry={nodes.High_Top_R.geometry} material={materials.MAT_Shoe_R} />
      <mesh geometry={nodes.Sole_Inside_R.geometry} material={materials.MAT_Sole_R} />
      <mesh geometry={nodes.Swoosh_R.geometry} material={materials.MAT_Shoe_R} />
      <mesh geometry={nodes.Sole_R.geometry} material={materials.MAT_Shoe_R} />
      <mesh geometry={nodes.Straps_R.geometry} material={materials.MAT_Shoe_R} />
      <mesh geometry={nodes.Leather_1_R.geometry} material={materials.MAT_Shoe_R} />
      <mesh geometry={nodes.Base_R.geometry} material={materials.MAT_Shoe_R} />
      <mesh geometry={nodes.Lace_Holder_R.geometry} material={materials.MAT_Shoe_R} />
    </group>
  )
}

useGLTF.preload('/Shoethelab.glb')
