/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\TheLabHub_V2.glb --transform --simplify 
Files: .\public\TheLabHub_V2.glb [38.25MB] > C:\Users\TresSillings\Projects\The Lab\the-lab-alpha\TheLabHub_V2-transformed.glb [2.56MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TheLabHub_V2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Center_floor.geometry} material={materials['Wet Asphalt Surface']} />
      <mesh geometry={nodes.Floor.geometry} material={materials['Wet Cracked Asphalt']} />
      <mesh geometry={nodes.Pillars.geometry} material={materials['Anthracite Grey Plastic']} />
      <mesh geometry={nodes.Roof.geometry} material={materials['Matte plastic plate with holes']} />
      <mesh geometry={nodes.arcade_3002_screen.geometry} material={materials['pantalas.001']} />
      <mesh geometry={nodes.Shoe_HitBox.geometry} material={materials.HitBox} position={[5.437, 1.607, 0.027]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['plastic.001']} />
      <mesh geometry={nodes.Cube018_1.geometry} material={materials['metal.001']} />
      <mesh geometry={nodes.Cube018_2.geometry} material={materials['covers .001']} />
      <mesh geometry={nodes.Cube018_3.geometry} material={materials['coin arcade.001']} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['buttons arcade.001']} />
      <mesh geometry={nodes.Cube019_1.geometry} material={materials['red plastic.001']} />
    </group>
  )
}

useGLTF.preload('/TheLabHub_V2-transformed.glb')