/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/TheLabHub_V2.glb --transform --keepnames --keepmeshes --shadows 
*/

import React, { useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model({ onProjectSelect, activeProject, ...props }) {
  const { nodes, materials } = useGLTF('/TheLabHub_V2-transformed.glb')

  // --- 1. INTERACTION LOGIC ---
  const [hovered, setHover] = useState(null)
  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto'
  }, [hovered])

  // Helper to bind clicks to projects
  const bindProject = (name) => ({
    onClick: (e) => { e.stopPropagation(); onProjectSelect(name) },
    onPointerOver: () => setHover(true),
    onPointerOut: () => setHover(false),
    visible: false // Set to true if you want to see the pink click zones
  })

  return (
    <group {...props} dispose={null}>
      
      {/* --- 2. HITBOXES (Mapped & Interactive) --- */}
      <mesh name="HitBox_01" castShadow receiveShadow geometry={nodes.HitBox_01.geometry} material={materials.HitBox1} position={[5.437, 1.302, 0.027]} {...bindProject('shoe')} />
      <mesh name="HitBox_02" castShadow receiveShadow geometry={nodes.HitBox_02.geometry} material={materials.HitBox1} position={[3.825, 1.302, 3.864]} {...bindProject('watch')} />
      <mesh name="HitBox_03" castShadow receiveShadow geometry={nodes.HitBox_03.geometry} material={materials.HitBox1} position={[-0.027, 1.302, 5.437]} {...bindProject('project_03')} />
      <mesh name="HitBox_04" castShadow receiveShadow geometry={nodes.HitBox_04.geometry} material={materials.HitBox1} position={[-3.864, 1.302, 3.825]} {...bindProject('project_04')} />
      <mesh name="HitBox_05" castShadow receiveShadow geometry={nodes.HitBox_05.geometry} material={materials.HitBox1} position={[-5.437, 1.302, -0.027]} {...bindProject('project_05')} />
      <mesh name="HitBox_06" castShadow receiveShadow geometry={nodes.HitBox_06.geometry} material={materials.HitBox1} position={[-3.825, 1.302, -3.864]} {...bindProject('project_06')} />
      <mesh name="HitBox_07" castShadow receiveShadow geometry={nodes.HitBox_07.geometry} material={materials.HitBox1} position={[0.027, 1.302, -5.437]} {...bindProject('project_07')} />
      <mesh name="HitBox_08" castShadow receiveShadow geometry={nodes.HitBox_08.geometry} material={materials.HitBox1} position={[3.864, 1.302, -3.825]} {...bindProject('project_08')} />

      {/* --- 3. CAMERAS (Hidden Targets) --- */}
      <mesh name="cam_01" castShadow receiveShadow geometry={nodes.cam_01.geometry} material={nodes.cam_01.material} position={[2.895, 2.089, 0.072]} visible={false} />
      <mesh name="cam_02" castShadow receiveShadow geometry={nodes.cam_02.geometry} material={nodes.cam_02.material} position={[2.016, 2.11, 2.119]} scale={1.01} visible={false} />
      <mesh name="cam_03" castShadow receiveShadow geometry={nodes.cam_03.geometry} material={nodes.cam_03.material} position={[-0.073, 2.131, 2.953]} scale={1.02} visible={false} />
      <mesh name="cam_04" castShadow receiveShadow geometry={nodes.cam_04.geometry} material={nodes.cam_04.material} position={[-2.16, 2.152, 2.056]} scale={1.03} visible={false} />
      <mesh name="cam_05" castShadow receiveShadow geometry={nodes.cam_05.geometry} material={nodes.cam_05.material} position={[-3.01, 2.173, -0.075]} scale={1.04} visible={false} />
      <mesh name="cam_06" castShadow receiveShadow geometry={nodes.cam_06.geometry} material={nodes.cam_06.material} position={[-2.096, 2.194, -2.202]} scale={1.05} visible={false} />
      <mesh name="cam_07" castShadow receiveShadow geometry={nodes.cam_07.geometry} material={nodes.cam_07.material} position={[0.076, 2.215, -3.068]} scale={1.06} visible={false} />
      <mesh name="cam_08" castShadow receiveShadow geometry={nodes.cam_08.geometry} material={nodes.cam_08.material} position={[2.244, 2.236, -2.136]} scale={1.07} visible={false} />

      {/* --- 4. SCENE GEOMETRY --- */}
      <mesh name="Center_floor" castShadow receiveShadow geometry={nodes.Center_floor.geometry} material={materials['Wet Asphalt Surface']} />
      <mesh name="Floor" castShadow receiveShadow geometry={nodes.Floor.geometry} material={materials['Wet Cracked Asphalt']} />
      <mesh name="Pillars" castShadow receiveShadow geometry={nodes.Pillars.geometry} material={materials['Anthracite Grey Plastic']} />
      <mesh name="Roof" castShadow receiveShadow geometry={nodes.Roof.geometry} material={materials['Matte plastic plate with holes']} />
      <mesh name="Walls" castShadow receiveShadow geometry={nodes.Walls.geometry} material={materials['Wet Cracked Asphalt']} />
      <mesh name="Floor_Pad" castShadow receiveShadow geometry={nodes.Floor_Pad.geometry} material={materials['Wet Asphalt Surface']} />
      <mesh name="Orbit" castShadow receiveShadow geometry={nodes.Orbit.geometry} material={materials.Neon} rotation={[0, Math.PI / 2, 0]} />
      
      <group name="Shoe_Arcade" position={[5.328, 1.055, 0.047]}>
        <mesh name="Shoe_Arcade_1" castShadow receiveShadow geometry={nodes.Shoe_Arcade_1.geometry} material={materials['plastic.001']} />
        <mesh name="Shoe_Arcade_2" castShadow receiveShadow geometry={nodes.Shoe_Arcade_2.geometry} material={materials['metal.001']} />
        <mesh name="Shoe_Arcade_3" castShadow receiveShadow geometry={nodes.Shoe_Arcade_3.geometry} material={materials['covers .001']} />
        <mesh name="Shoe_Arcade_4" castShadow receiveShadow geometry={nodes.Shoe_Arcade_4.geometry} material={materials['coin arcade.001']} />
        <mesh name="Shoe_Arcade_5" castShadow receiveShadow geometry={nodes.Shoe_Arcade_5.geometry} material={materials['buttons arcade.001']} />
        <mesh name="Shoe_Arcade_6" castShadow receiveShadow geometry={nodes.Shoe_Arcade_6.geometry} material={materials['red plastic.001']} />
      </group>
      <mesh name="Shoe_Arcade_Screen" castShadow receiveShadow geometry={nodes.Shoe_Arcade_Screen.geometry} material={materials['pantalas.001']} position={[5.481, 1.295, -0.004]} />
      
      <group name="Watch_Arcade" position={[3.773, 0.968, 3.774]}>
        <mesh name="Watch_Arcade_1" castShadow receiveShadow geometry={nodes.Watch_Arcade_1.geometry} material={materials['plastic.001']} />
        <mesh name="Watch_Arcade_2" castShadow receiveShadow geometry={nodes.Watch_Arcade_2.geometry} material={materials['metal.001']} />
        <mesh name="Watch_Arcade_3" castShadow receiveShadow geometry={nodes.Watch_Arcade_3.geometry} material={materials['covers .001']} />
        <mesh name="Watch_Arcade_4" castShadow receiveShadow geometry={nodes.Watch_Arcade_4.geometry} material={materials['buttons arcade.001']} />
        <mesh name="Watch_Arcade_5" castShadow receiveShadow geometry={nodes.Watch_Arcade_5.geometry} material={materials['coin arcade.001']} />
        <mesh name="Watch_Arcade_6" castShadow receiveShadow geometry={nodes.Watch_Arcade_6.geometry} material={materials['red plastic.001']} />
      </group>
      <mesh name="Watch_Arcade_Screen" castShadow receiveShadow geometry={nodes.Watch_Arcade_Screen.geometry} material={materials['pantalas.001']} position={[4.019, 1.342, 4.027]} />

      <group name="AWEBCO_Arcade_01" position={[-0.049, 0.905, 5.15]}>
        <mesh name="AWEBCO_Arcade_01_1" castShadow receiveShadow geometry={nodes.AWEBCO_Arcade_01_1.geometry} material={materials['metal.001']} />
        <mesh name="AWEBCO_Arcade_01_2" castShadow receiveShadow geometry={nodes.AWEBCO_Arcade_01_2.geometry} material={materials['covers .001']} />
        <mesh name="AWEBCO_Arcade_01_3" castShadow receiveShadow geometry={nodes.AWEBCO_Arcade_01_3.geometry} material={materials['plastic.001']} />
        <mesh name="AWEBCO_Arcade_01_4" castShadow receiveShadow geometry={nodes.AWEBCO_Arcade_01_4.geometry} material={materials.pantalas} />
        <mesh name="AWEBCO_Arcade_01_5" castShadow receiveShadow geometry={nodes.AWEBCO_Arcade_01_5.geometry} material={materials['coin arcade.001']} />
        <mesh name="AWEBCO_Arcade_01_6" castShadow receiveShadow geometry={nodes.AWEBCO_Arcade_01_6.geometry} material={materials['buttons arcade.001']} />
        <mesh name="AWEBCO_Arcade_01_7" castShadow receiveShadow geometry={nodes.AWEBCO_Arcade_01_7.geometry} material={materials['red plastic.001']} />
      </group>

      <mesh name="DraftingTableStand_1" castShadow receiveShadow geometry={nodes.DraftingTableStand_1.geometry} material={materials['DraftingTable.Wood1']} />
      <mesh name="DraftingTableStand_2" castShadow receiveShadow geometry={nodes.DraftingTableStand_2.geometry} material={materials['DraftingTable.Wood2']} />
      <mesh name="DraftingTableStand_3" castShadow receiveShadow geometry={nodes.DraftingTableStand_3.geometry} material={materials['DraftingTable.Metal']} />
      <mesh name="DraftingTableSurface_1" castShadow receiveShadow geometry={nodes.DraftingTableSurface_1.geometry} material={materials['DraftingTable.Wood1']} />
      <mesh name="DraftingTableSurface_2" castShadow receiveShadow geometry={nodes.DraftingTableSurface_2.geometry} material={materials['DraftingTable.Wood2']} />
      <mesh name="DraftingTableSurface_3" castShadow receiveShadow geometry={nodes.DraftingTableSurface_3.geometry} material={materials['DraftingTable.Metal']} />
    </group>
  )
}

useGLTF.preload('/TheLabHub_V2-transformed.glb')