/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\planet_01.glb --transform --keepnames --keepmeshes --shadows 
Files: .\planet_01.glb [391.17KB] > C:\Users\TresSillings\Projects\The Lab\the-lab-alpha\planet_01-transformed.glb [124.77KB] (68%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/planet_01-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sphere003" rotation={[-0.235, -0.877, 1.269]}>
        <mesh name="Sphere003_1" castShadow receiveShadow geometry={nodes.Sphere003_1.geometry} material={materials['Material.001']} />
        <mesh name="Sphere003_2" castShadow receiveShadow geometry={nodes.Sphere003_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}
export default Model

useGLTF.preload('/planet_01-transformed.glb')
