/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Asteroid.glb --transform --keepnames --keepmeshes --shadows 
Files: .\Asteroid.glb [13.12KB] > C:\Users\TresSillings\Projects\The Lab\the-lab-alpha\Asteroid-transformed.glb [11.71KB] (11%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Asteroid-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Asteroid" castShadow receiveShadow geometry={nodes.Asteroid.geometry} material={materials.body} position={[7.367, 4.102, 1.379]} scale={0.457} />
    </group>
  )
}
export default Model

useGLTF.preload('/Asteroid-transformed.glb')
