/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\EnviromentAwebco.glb --transform 
Files: .\public\EnviromentAwebco.glb [18.51MB] > C:\Users\TresSillings\Projects\The Lab\the-lab-alpha\EnviromentAwebco-transformed.glb [986.81KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/EnviromentAwebco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.TechFloor} scale={8.928} />
      <mesh geometry={nodes.rock_big_1.geometry} material={materials.Rock} position={[-4.394, 0.021, -4.769]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.BézierCircle.geometry} material={materials.PaletteMaterial001} position={[1.563, 0.455, -2.605]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.BézierCurve001.geometry} material={materials.PaletteMaterial002} position={[1.324, 0.142, -2.68]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial003} position={[1.563, 0.49, -2.605]} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}
export default Model

useGLTF.preload('/EnviromentAwebco-transformed.glb')
