/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\Floor.glb --transform 
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function Floor(props) {
  const { nodes, materials } = useGLTF('/Floor-transformed.glb')

  // Kill the "strange lines" and Moiré patterns on the floor
  useEffect(() => {
    if (materials.TechFloor && materials.TechFloor.map) {
      materials.TechFloor.map.minFilter = THREE.LinearMipmapLinearFilter;
      materials.TechFloor.map.anisotropy = 16; // Essential for flat planes viewed at angles
    }
  }, [materials])

  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Plane.geometry} 
        material={materials.TechFloor} 
        scale={8.928} 
        receiveShadow 
      />
    </group>
  )
}

useGLTF.preload('/Floor-transformed.glb')