/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\planet_01.glb --transform --keepnames --keepmeshes --shadows 
Files: .\planet_01.glb [1.02MB] > C:\Users\TresSillings\Projects\The Lab\the-lab-alpha\planet_01-transformed.glb [359.79KB] (65%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/planet_01-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Bone001" position={[0.08, 1.238, 6.509]} rotation={[1.057, -0.678, 0.302]} scale={0.1}>
        <group name="Bone" position={[0, 1.891, 0]} rotation={[Math.PI / 2, -0.459, Math.PI / 2]}>
          <group name="Bone002" position={[0, 0.218, 0.471]} rotation={[0.334, -1.462, -Math.PI]}>
            <mesh name="piston_shaft" castShadow receiveShadow geometry={nodes.piston_shaft.geometry} material={materials.PaletteMaterial001} position={[-1.396, 0.25, -0.76]} rotation={[-2.419, 0.743, -1.774]} />
          </group>
          <mesh name="Circle002" castShadow receiveShadow geometry={nodes.Circle002.geometry} material={materials.PaletteMaterial001} position={[0, -0.834, 1.689]} rotation={[-1.112, 0, 0]} />
          <mesh name="Cylinder" castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials.PaletteMaterial001} position={[0, -0.834, 1.689]} rotation={[-1.112, 0, 0]} />
          <group name="satalite_dish" position={[0, -0.834, 1.689]} rotation={[-1.112, 0, 0]}>
            <mesh name="Sphere004" castShadow receiveShadow geometry={nodes.Sphere004.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Sphere004_1" castShadow receiveShadow geometry={nodes.Sphere004_1.geometry} material={materials.PaletteMaterial003} />
            <mesh name="Sphere004_2" castShadow receiveShadow geometry={nodes.Sphere004_2.geometry} material={materials.PaletteMaterial002} />
            <mesh name="Sphere004_3" castShadow receiveShadow geometry={nodes.Sphere004_3.geometry} material={materials.PaletteMaterial004} />
          </group>
        </group>
        <group name="Bone003" position={[-0.11, 1.528, 0]} rotation={[1.673, -0.124, 1.583]}>
          <group name="piston" position={[-1.495, -0.297, 0]} rotation={[-1.571, -0.124, -1.571]}>
            <mesh name="Circle001" castShadow receiveShadow geometry={nodes.Circle001.geometry} material={materials.PaletteMaterial001} />
            <mesh name="Circle001_1" castShadow receiveShadow geometry={nodes.Circle001_1.geometry} material={materials.PaletteMaterial003} />
          </group>
        </group>
        <group name="satalite_base" position={[0, 0.007, 0]} rotation={[0, -1.571, 0]}>
          <mesh name="Circle" castShadow receiveShadow geometry={nodes.Circle.geometry} material={materials.PaletteMaterial002} />
          <mesh name="Circle_1" castShadow receiveShadow geometry={nodes.Circle_1.geometry} material={materials.PaletteMaterial003} />
        </group>
      </group>
      <group name="Sphere003" position={[0.383, 0.55, 5.811]} rotation={[-0.235, -0.877, 1.269]}>
        <mesh name="Sphere003_1" castShadow receiveShadow geometry={nodes.Sphere003_1.geometry} material={materials['Material.001']} />
        <mesh name="Sphere003_2" castShadow receiveShadow geometry={nodes.Sphere003_2.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh name="pTorus1_body_0002" castShadow receiveShadow geometry={nodes.pTorus1_body_0002.geometry} material={materials.PaletteMaterial002} position={[-0.192, 0.661, 5.081]} rotation={[-0.235, -0.877, 1.269]} scale={0.005} />
      <mesh name="pTorus1_gem_0002" castShadow receiveShadow geometry={nodes.pTorus1_gem_0002.geometry} material={materials.PaletteMaterial003} position={[-0.192, 0.661, 5.081]} rotation={[-0.235, -0.877, 1.269]} scale={0.005} />
    </group>
  )
}

export default Model;
useGLTF.preload('/planet_01-transformed.glb')
