/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Rocket.glb --transform --keepnames --keepmeshes --shadows 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rocket-transformed.glb')
  const flameRef = useRef()

  // 1. Engine Animation Logic
  useFrame((state) => {
    if (flameRef.current) {
      // Pulsing effect using Sine wave for the "flicker"
      const s = 1 + Math.sin(state.clock.elapsedTime * 20) * 0.1
      flameRef.current.scale.set(s, s * 1.5, s)
      
      // Dynamic intensity to match the brand energy
      flameRef.current.material.emissiveIntensity = 2 + Math.sin(state.clock.elapsedTime * 10)
    }
  })

  return (
    <group {...props} dispose={null}>
      {/* Hero Rocket Mesh Group */}
      <group name="Object_59_Plastic_(1)_0" rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.057}>
        <mesh name="Object_59_Plastic_(1)_0_1" castShadow receiveShadow geometry={nodes['Object_59_Plastic_(1)_0_1'].geometry} material={materials.Plastic_1} />
        <mesh name="Object_59_Plastic_(1)_0_2" castShadow receiveShadow geometry={nodes['Object_59_Plastic_(1)_0_2'].geometry} material={materials.Plastic} />
        <mesh name="Object_59_Plastic_(1)_0_3" castShadow receiveShadow geometry={nodes['Object_59_Plastic_(1)_0_3'].geometry} material={materials.Plastic_2} />
        <mesh name="Object_59_Plastic_(1)_0_4" castShadow receiveShadow geometry={nodes['Object_59_Plastic_(1)_0_4'].geometry} material={materials.Plastic_3} />
        <mesh name="Object_59_Plastic_(1)_0_5" castShadow receiveShadow geometry={nodes['Object_59_Plastic_(1)_0_5'].geometry} material={materials.Metal_1} />
      </group>

      {/* 2. Integrated Engine Flame Mesh */}
      <mesh ref={flameRef} position={[0, -1.0, 0]} rotation={[Math.PI, 0, 0]}>
        <coneGeometry args={[0.25, 0.8, 8]} />
        <meshStandardMaterial 
          color="#CC3333" // AWEBCO Red
          emissive="#CC3333" 
          emissiveIntensity={2} 
          transparent 
          opacity={0.8} 
        />
      </mesh>
    </group>
  )
}

export default Model
useGLTF.preload('/Rocket-transformed.glb')