/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Rocket.glb --transform --keepnames --keepmeshes --shadows 
*/

import React, { useRef, forwardRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

// Wrapped in forwardRef so the Experience.jsx can control its position
export const Model = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('/Rocket-transformed.glb')
  const flameRef = useRef()
  const scroll = useScroll()

  useFrame((state) => {
    if (flameRef.current) {
      const offset = scroll.offset // 0 to 1

      // --- ENGINE STATE LOGIC ---
      // 1. IDLE: offset < 0.05 (Subtle breathing)
      // 2. LIFTOFF: offset 0.05 to 0.4 (Maximum power/shake)
      // 3. FLYING: offset > 0.4 (Steady propulsion)
      
      const isLifting = offset > 0.05 && offset < 0.4
      const isFlying = offset >= 0.4

      // Dynamic Flame Scaling
      const baseScale = isLifting ? 3.0 : (isFlying ? 1.8 : 1.0)
      const flicker = 1 + Math.sin(state.clock.elapsedTime * 30) * 0.15
      
      flameRef.current.scale.set(
        flicker, 
        baseScale * flicker, 
        flicker
      )

      // Brand Red Glow Intensity
      // Boosts to 10 during liftoff for that "BOOM" energy
      flameRef.current.material.emissiveIntensity = isLifting 
        ? 10 + Math.sin(state.clock.elapsedTime * 40) * 5 
        : 2 + Math.sin(state.clock.elapsedTime * 10)
    }
  })

  return (
    <group ref={ref} {...props} dispose={null}>
      {/* Hero Rocket Mesh Group */}
      <group name="Object_59_Plastic_(1)_0" rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.057}>
        <mesh name="Object_59_Plastic_(1)_0_1" castShadow receiveShadow geometry={nodes['Object_59_Plastic_(1)_0_1'].geometry} material={materials.Plastic_1} />
        <mesh name="Object_59_Plastic_(1)_0_2" castShadow receiveShadow geometry={nodes['Object_59_Plastic_(1)_0_2'].geometry} material={materials.Plastic} />
        <mesh name="Object_59_Plastic_(1)_0_3" castShadow receiveShadow geometry={nodes['Object_59_Plastic_(1)_0_3'].geometry} material={materials.Plastic_2} />
        <mesh name="Object_59_Plastic_(1)_0_4" castShadow receiveShadow geometry={nodes['Object_59_Plastic_(1)_0_4'].geometry} material={materials.Plastic_3} />
        <mesh name="Object_59_Plastic_(1)_0_5" castShadow receiveShadow geometry={nodes['Object_59_Plastic_(1)_0_5'].geometry} material={materials.Metal_1} />
      </group>

      {/* Integrated Engine Flame Mesh */}
      <mesh ref={flameRef} position={[0, -1.6, 0]} rotation={[Math.PI, 0, 0]}>
        <coneGeometry args={[0.25, 0.8, 8]} />
        <meshStandardMaterial 
          color="#CC3333" // AWEBCO Red
          emissive="#CC3333" 
          transparent 
          opacity={0.9} 
        />
      </mesh>
    </group>
  )
})

export default Model
useGLTF.preload('/Rocket-transformed.glb')